preload = /home/psyphi/Pictures/wall.jpg

#set the default wallpaper(s) seen on initial workspace(s) --depending on the number of monitors used
wallpaper {
    monitor =  eDP-1
    fit_mode = contain
    path = /home/psyphi/Pictures/wall.jpg
}
#enable splash text rendering over the wallpaper
splash = true

#fully disable ipc
# ipc = off
